iglu-gw:
    env: IGLU_GW-v0
    run: IMPALA
    stop:
        timesteps_total: 1000000000
    checkpoint_at_end: True
    checkpoint_freq: 1000 # roughly each 5000k steps
    config:
        env_config: 
          action_space: human-level
          visual: true
          size_reward: true
          time_limit: 500
          # possible values are: 'one_task', 'many_tasks', 'random_tasks'
          task_mode: one_task 
          # if task_mode is one_task -> string with task id
          # if task_mode is many_tasks -> list of task ids
          # if task_mode is random_tasks -> ignored
          task_id: C32
          # only used if task_mode is random_tasks
          random_tasks:
            max_blocks: 20
            height_levels: 2
            allow_float: false
            max_dist: 7
            num_colors: 6
            max_cache: 1
        model:
          custom_model: grid_baseline_model
          use_lstm: True
        framework: torch
        vtrace: True
        vtrace_clip_rho_threshold: 1.0
        vtrace_clip_pg_rho_threshold: 1.0
        rollout_fragment_length: 100
        train_batch_size: 5000
        num_workers: 20
        num_envs_per_worker: 64
        num_gpus: 1
        broadcast_interval: 1
        max_sample_requests_in_flight_per_worker: 2 
        num_multi_gpu_tower_stacks: 10
        
        replay_proportion: 1.0
        replay_buffer_num_slots: 100
        learner_queue_timeout: 100000
        minibatch_buffer_size: 10
        learner_queue_size: 32
        num_sgd_iter: 5
        lr_schedule: [
            [0, 0.0005],
            [150000000, 0.000001],
        ]
        vf_loss_coeff: 0.5
        entropy_coeff: 0.01
        grad_clip: 100.0
        evaluation_num_workers: 3
        evaluation_interval: 10
        evaluation_num_episodes: 3
        evaluation_config:
          input: sampler
          explore: false
