# Runs on a single g3.16xl node
# See https://github.com/ray-project/rl-experiments for results
iglu-gw:
    env: IGLU_GW-v0
    run: PPO
    stop:
        timesteps_total: 200000000
    checkpoint_at_end: True
    checkpoint_freq: 200 # roughly each 5m steps
    config:
        env_config:
            visual: false
            log: false
            size_reward: false
            name: train
            right_placement_scale: 1.0
            wrong_placement_scale: 0.0
        framework: torch
        lambda: 0.95
        kl_coeff: 0.5
        clip_rewards: True
        clip_param: 0.2
        vf_clip_param: 20.0
        entropy_coeff: 0.03
        train_batch_size: 10000
        rollout_fragment_length: 100
        sgd_minibatch_size: 500
        num_sgd_iter: 10
        num_workers: 10
        num_envs_per_worker: 32
        batch_mode: truncate_episodes
        observation_filter: NoFilter
        evaluation_num_workers: 1
        # evaluation_num_envs_per_worker: 1
        evaluation_interval: 1
        evaluation_num_episodes: 10
        evaluation_config:
            input: sampler
            explore: true
            env_config:
                visual: true
                log: True
                logdir: "./eval_logs"
                name: eval
                size_reward: false
                right_placement_scale: 100.0
                wrong_placement_scale: 1.0
        model:
            custom_model: grid_baseline_model
            use_lstm: True
            vf_share_layers: true
        num_gpus: 1
